drive_encryption.c

Casting void pointer to __u64 works for 64-bit arch but fails to compile on 32-bit arch like i686.
Fail on i686 platform:
drive_encryption.c: In function ‘nvme_security_recv_ioctl’: drive_encryption.c:236:25: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
236 |         nvme_cmd.addr = (__u64)response_buffer;
|                         ^
drive_encryption.c: In function ‘nvme_identify_ioctl’:
drive_encryption.c:271:25: error: cast from pointer to integer of
different size [-Werror=pointer-to-int-cast]
271 |         nvme_cmd.addr = (__u64)response_buffer;
|                         ^
cc1: all warnings being treated as errors
make: *** [Makefile:211: drive_encryption.o] Error 1
This change adds cast void pointer to uintptr_t first to ensure that proper …

mdadm: Fix compilation for 32-bit arch

---

Assemble.c
Dump.c
Grow.c
config.c
mdstat.c
super-ddf.c
super-intel.c

There are a few places we don't check the return status when calling fstat for success. Clean up the calls by adding a check before continuing.
V2: clean up warnings/errors from checkpatch.pl

add checking of return status on fstat calls

---

super-intel.c

Execution cannot reach this statement: "while (devlist) { dv = de...". Local variable "err" is assigned only once, to a constant value, making it effectively constant throughout its scope. Remove dead code.

mdadm: super-intel remove dead code

---

super-intel.c

In the expression "1 << i", left shifting by more than 31 bits has undefined behavior. The shift amount, "i", is as much as 63. The operand has type "int" (32 bits) and will be shifted as an "int". The fix is to change to a 64 bit int.

mdadm: super-intel fix bad shift

---

Makefile

Only check the first word of MAKEFLAGS for 's', that's where all the single letter options are collected.
MAKEFLAGS contains _all_ make flags, so if any command line argument contains a letter 's', the silent test will be false positive.  Think e.g. make 'DESTDIR=.../aports/main/mdadm/pkg/mdadm' install

Makefile: fix make -s detection

---

super-intel.c

Autolayout_imsm() is not executed if `IMSM_NO_PLATFORM=1` is set. This causes that first volume cannot be created. Disk for new volume are never configured.
Fix it by making autolayout_imsm() independent from super->orom because NULL there means that `IMSM_NO_PLATFORM=1` is set. There are not platform restrictions to create volume, we just analyze drives. It is safe.
Fixes: 6d4d9ab295de ("imsm: use same slot across container")

imsm: fix first volume autolayout with IMSM_NO_PLATFORM

---

super-intel.c

Autolayout_imsm() shall be executed when IMSM_NO_PLATFORM=1 is set. It was fixed by listed commit, checking super->orom was removed, but also checking freesize. Freesize is not set for operations on RAID volume with no size update, that's why it is not required to have this value and always run autolayout_imsm().
Fix it by making autolayout_imsm() dependent on freesize.
Fixes: [46f192](https://github.com/md-raid-utilities/mdadm/commit/46f19270265fe54cda1c728cb156b755273b4ab6) ("imsm: fix first volume autolayout with IMSM_NO_PLATFORM")

imsm: make freesize required to volume autolayout

---

test
tests/func.sh

Commit 4c12714d1ca0 ("test: run tests on system level mdadm") removed MDADM_NO_SYSTEMCTL flag from test suite. This causes imsm tests to fail as mdadm no longer triggers mdmon and flags exists only within session.
Use systemd set/unset-environment to pass necessary flags.
Introduce colors to grab users attention to warnings and key messages.
Make test suite setup systemd environment.
Add setup/clean_systemd_env() functions.
Warn user about altering systemd environment.
Add colors to success/fail messages and warnings.

test: pass flags to services

---

msg.c

While creating an IMSM RAID, mdadm will wait for the mdmon main process to finish if mdmon runs in forking mode. This is because with "Type=forking" in the mdmon service unit file, "systemctl start service" will block until the main process of mdmon exits. At that moment, mdmon has already created the socket, so the subsequent socket connect from mdadm will succeed.
However, when mdmon runs in foreground mode (without "Type=forking" in the service unit file), "systemctl start service" will return once the mdmon process starts. This causes mdadm and mdmon to run in parallel, which may lead to a socket connection failure since mdmon has not yet initialized the socket when mdadm tries to connect. If the next instruction/command is to access this device and try to write to it, a permission …

mdadm: Fix socket connection failure when mdmon runs in foreground mode.

---

Makefile

When mdadm is compiled with clang, direct gcc will fail. Make sure to use $(CC) variable instead.
Note that Clang does not support --help=warnings,
--print-diagnostic-options should be used instead. So with Clang, the compilation will go through, but the extra warning flags will never be added.
New PR to fix merge.

Makefile: Do not call gcc directly (v2)

---

msg.c

Reverts md-raid-utilities/mdadm#24
@shmsingh I was over optimistic and this change is not ready. The first is that I suggested you to use `for` and I didn't notice that you use `errno` in error message so I gives us following error:
``` mdadm: Failed to connect to control socket. (Success!!)  ```
If timeout is reached, errno contains last `usleep()` result.
We can fix that. Not a big deal. There are more critical problem:
It looks like that `ping_monitor()` is called multiple times not as a hard requirement for monitor to be. As a result, the console is frozen for 2 seconds on various commands. This is not acceptable.
For example:
- creation of volume (Looks simple to fix but it is not, `need_mdmon` logic is not complete)
- stopping raids (Manage_stop)
- reshape flows (Grow.c file)
- …

Revert "mdadm: Fix socket connection failure when mdmon runs in foreground mode."

---

config.c

Fix memory leak in load_containers() in config.c reported by SAST analysis.

config.c: Fix memory leak in load_containers()

---

Build.c

Event leaked_handle: Handle variable "bitmap_fd" going out of scope leaks the handle.

mdadm: Build.c fix coverity issues

---

Create.c

* Event negative_returns: "fd" is passed to a parameter that cannot be negative. Which is set to -1 to start.
* Event open_fn: Returning handle opened by "open_dev_excl".
* Event var_assign: Assigning: "container_fd" = handle returned from "open_dev_excl(st->container_devnm)"
* Event leaked_handle: Handle variable "container_fd" going out of scope leaks the handle

mdadm: Create.c fix coverity issues

---

mapfile.c

Fix STRING_OVERFLOW issue found by SAST analysis in map_add() and map_update() in mapfile.c.

mapfile.c: Fix STRING_OVERFLOW issue

---

Manage.c

Fix `for` to make --set-faulty working.
Fixes: 1b4b73fd535a ("mdadm: Manage.c fix coverity issues")

Manage: fix is_remove_safe()

---

super-intel.c

Improve readability of the output. Result after change from `mdadm --detail-platform`
```
I/O Controller : /sys/devices/pci0000:17/0000:17:05.5 (VMD)
NVMe under VMD : /dev/nvme3n1 (PHLF737200841P0GGN)
Encryption(Ability|Status): None|Unencrypted
NVMe under VMD : /dev/nvme6n1 (PHLJ915002N81P0FGN)
Encryption(Ability|Status): None|Unencrypted
NVMe under VMD : /dev/nvme2n1 (PHLJ915000811P0FGN)
Encryption(Ability|Status): None|Unencrypted
NVMe under VMD : /dev/nvme5n1 (PHLJ914600DV1P0FGN)
Encryption(Ability|Status): None|Unencrypted
NVMe under VMD : /dev/nvme4n1 (PHLJ915003221P0FGN)
Encryption(Ability|Status): None|Unencrypted
```

imsm: add indent for encryption details

---

Query.c

* Event leaked_storage: Variable "sra" going out of scope leaks the storage it points to.
* Event uninit_use_in_call: Using uninitialized value "larray_size" when calling "human_size_brief".

mdadm Query.c fix coverity issues

---

lib.c

* Event fixed_size_dest: You might overrun the 32-character fixed-size string "devnm" by copying "cp + 1" without checking the length.
* Event fixed_size_dest: You might overrun the 32-character fixed-size string "devnm" by copying "cp" without checking the length.

mdadm lib.c fix coverity issues

---

Detail.c

Mentioned commit (see Fixes) causes that devices with UUID equal to uuid_zero was not recognized properly. For few devices the first one was taken always, and the same information was printed. It caused regression, when few containers were created, symlinks were generated only for the first one.
Add checking if uuid is uuid_zero and, if yes, use devname to differentiate devices.
Fixes: 60c19530dd7c ("Detail: remove duplicated code")

Detail: fix --detail --export for uuid_zero

---

.github/workflows/review.yml
Makefile
mdadm.h
super0.c

It is essential to avoid vulnerabilities in code as much
as possible using safe compilation flags. It is easier if
they are added to the Makefile and applied during compilation.
Add new gcc flags and make them configurable, because they
may not be supported for some compilers.
Unset preconfigured FORTIFY_SOURCE, which caused build errors
when built-in flag was used with the same value.
Fix error reported when those additional flags were used.

Compiler flags

---

Assemble.c
Incremental.c
Manage.c
Monitor.c
config.c
mapfile.c
mdadm.h
mdmon.c
mdmon.h
mdstat.c
super-intel.c
util.c

To avoid repeating `mdstat_read()` in `IncrementalRemove()`, new function `mdstat_find_by_member_name()` has been proposed. With that, `IncrementalRemove()` handles own copy of mdstat content and there is no need to repeat reading for external stop.
Additionally, It proposed few helper to avoid repeating `ent->metadata_version` checks across code.
Tested by:
- `mdadm -If nvme0n1` - This involves testing `mdstat_find_by_member_name()`
- `mdadm -G -l0 /dev/md126` - This involves `mdadm_by_subdev()`

mdstat: Rework mdstat external ararys handling

---

managemon.c

* Event check_return: Calling "fcntl(fd, 4, fl)" without checking return value. This library function may fail and return an error code.
* Event check_after_deref: Null-checking "new" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.

mdadm managemon.c fix coverity issues

---

msg.c

* Event check_return: Calling "fcntl(sfd, 4, fl)" without checking return value. This library function may fail and return an error code.

mdadm: msg.c fix coverity issues

---

policy.c

Refactor Write_rules() in policy.c to eliminate check_return issue found by SAST analysis.

policy.c: Fix check_return issue in Write_rules()

---

super-gpt.c

Fix check_return issue in load_gpt() reported by SAST analysis in super-gpt.c.

super-gpt.c: Fix check_return issue in load_gpt()

---

.github/workflows/review.yml
super-intel.c

Fix compilation error. Set bit migr_state instead of assigning int
value.
Fix review.yml file, update gcc version used to build for each configuration from matrix.
Add new released gcc to compilation test during GH action.
Change runner to Ubuntu 24.04 which supports gcc versions up to 14.
Previously ubuntu-latest was used (22.04) which didn't support gcc 13
and 14. Add verification if correct gcc was installed during test.

Fix compilation error for gcc14

---

Grow.c

Component_size couldn't be set using ioctl when new drive size is big (e.g. 5TB). Command value is bigger than 32 bits and error is reported
- it is known ioctl limitation. Remove updating array properties using ioctl, use sysfs instead. Sysfs was introduced in 3.10, so now it is old enough to be safely used. Array_size in sysfs should be set for every size change for external metadata, when grow is performed without errors.

Grow_reshape: set only component_size for size grow

---

mdstat.c

Move `ent = ent->next;` to while. It was outside the loop so if there are more than 2 elements and we are looking for 3rd element it causes infinite loop..
Fix `el->next` zeroing. It causes segfault in mdstat_free(). Theses issues were not visible in my testing because I had only 2 MD devices.

mdstat: fix list detach issues

---

md.4

There is a wrong word in the `md(4)` man page; the commit in this pull request corrects it.

md.4: replace wrong word

---

util.c

* Event check_return: Calling "open" without checking return value
* Event check_return: Calling "lseek(fd, sector_size, 0)" without checking return value.
* Event leaked_handle: Handle variable "fd" going out of scope leaks the handle.
* Event leaked_storage: Variable "dir" going out of scope leaks the storage it points to.
* Event fixed_size_dest: You might overrun the 32-character fixed-size string "st->devnm" by copying "_devnm" without checking the length.
* Event fixed_size_dest: You might overrun the 32-character fixed-size string "container" by copying "dev" without checking the length.

mdadm: util.c fix coverity issues

---

sysfs.c

* Event fixed_size_dest: You might overrun the 32-character fixed-size string "mdi->sys_name" by copying "devnm" without checking the length
* Event fixed_size_dest: You might overrun the 50-character fixed-size string "sra->text_version" by copying "buf + 9" without checking the length.
* Event string_overflow: You might overrun the 32-character destination string "dev->sys_name" by writing 256 characters from "de->d_name".

mdadm: sysfs.c fix coverity issues

---

platform-intel.c
platform-intel.h
super-intel.c

dprintf() call in path_attached_to_hba() is too noisy. Remove the call and refactor the function. Remove obsolete env variables check.

platform-intel: refactor path_attached_to_hba()

---

Detail.c

The counts of active, working, failed and spare devices were not printed when the number was zero.
Refactor the code to always display the counts of all device types, regardless of their number. This way, it is more reliable for users.

mdadm: Change displaying of devices in --detail

---

platform-intel.c
super-intel.c

These drives are not supported, remove warning.
It also adds 3th party nvmes support for NVMe orom, verification was skipped anyway.
Tested on my setup:
```bash
mdadm: imsm capabilities not found for controller: /sys/devices/pci0000:00/0000:00:17.0 (type SATA)
mdadm: imsm capabilities not found for controller: /sys/devices/pci0000:00/0000:00:11.5 (type SATA)
Platform : Intel(R) Rapid Storage Technology enterprise
RAID Levels : raid0 raid1 raid5 raid10
Chunk Sizes : 4k 8k 16k 32k 64k 128k
2TB volumes : supported
2TB disks : supported
Max Disks : 12
Max Volumes : 2 per array, 12 per platform
3rd party NVMe : supported
NVMe Device : /dev/nvme1n1 (PHLJ914600HV1P0FGN)
Encryption(Ability|Status): None|Unencrypted
Platform : Intel(R) Virtual RAID on CPU
Version : 8.0.0.1386
RAID Levels : raid0 …
```

imsm: remove Intelx8 drives warning

---

super-intel.c

If reshape (eg. chunksize migration) is gracefully stopped via SIGTERM the checkpoint is not saved and reshape cannot be resumed due to "data being present in copy area". This is because UNIT_SRC_NORMAL isn't set if SIGTERM occured.
Move SIGTERM handling at the end of the loop to allow saving checkpoint (and state) so reshapes can be properly resumed.

imsm: save checkpoint prior to exit

---

Examine.c
dlink.c
dlink.h

Fix memory leaks in Examine() reported by SAST analysis. Implement a method to traverse and free all the nodes of the doubly linked list. Replace for loop with while loop in order to improve redability of the code and free allocated memory correctly.

Examine.c: Fix memory leaks in Examine()

---

dlink.h

Checkpatch issued a warning due to missing function argument names. Add the names to resolve the warnings.

dlink.h: Fix checkpatch warnings for function args

---

Incremental.c
mdadm.h
udev-md-raid-assembly.rules

There are no reasons to keep this interface different than others. Allow to use devnode but keep old way for backward compatibility. Method is added to verify that only devnode or kernel name is used.
Testing on my setup passed. I used raid0, so removal failed, but I checked parsing.
```bash
[gklab-localhost ~/mtkaczyk_work/mdadm/mdadm-github]# ./mdadm -If /dev/nvme5n1
mdadm: set device faulty failed for nvme5n1:  Device or resource busy
mdadm: nvme5n1 is still in use, cannot remove.
[gklab-localhost ~/mtkaczyk_work/mdadm/mdadm-github]# ./mdadm -If /dev/md/nvme5n1
mdadm: Cannot remove "/dev/md/nvme5n1", devnode path or kernel device name is allowed.
[gklab-localhost ~/mtkaczyk_work/mdadm/mdadm-github]# ./mdadm -If /dev/disk/by-path/pci-0000\:00\:11.5-ata-5-part4
mdadm: Cannot remove …
```

Incremental: support devnode in IncrementalRemove.

---

util.c

Fix divide_by_zero issue reported by SAST analysis in Detail.c when calling enough() from util.c. Also add missing spaces for better code readability.

Detail.c: Fix divide_by_zero issue

---

.github/tools/install_ubuntu_packages.sh

Updating all of the packages every time is not needed and costs a lot of resources. Remove it.

CI: remove apt update from steps

---

Monitor.c

Commit a07dea8d3b78 ("Mdmonitor: Refactor check_one_sharer() for better error handling") introduced an issue, if directory /run/mdadm is missing, monitor fails to start. Move the directory creation earlier to ensure it is always created.

Mdmonitor: Fix startup with missing directory

---

md.4

Documentation/md has moved to Documentation/driver-api/md. Update it.
Fixes #83

md.man: update refference to raid5-ppl.rst

---

util.c

Instead of "remove", "faulty" was called.
Fixes: d95edceb362a ("sysfs: add function for writing to sysfs fd")

util: fix sys_hot_remove_disk()

---

mdadm.8.in
mdadm.conf.5.in

The `--udev-rules` flag was barely mentioned under manuals, so I added a bit into both.

Improve mdadm and mdadm.conf manuals

---

Grow.c

Correcting the terminology on the output when doing a takeover vs a reshape.

mdadm: Grow.c distinguish takeover from reshape on grow operation

---

Manage.c
mdadm.h
sysfs.c

Function is added to not repeat defining "dev-%s", disk_name. Related code branches are updated. No functional changes.
Preliminary tested:
```bash
Personalities : [raid6] [raid5] [raid4] [raid1]
md126 : active (auto-read-only) raid1 nvme4n1[1] nvme6n1[0]
5242880 blocks super external:/md127/0 [2/2] [UU]
md127 : inactive nvme6n1[1](S) nvme4n1[0](S)
10402 blocks super external:imsm
unused devices: <none>
mdadm: Cannot remove /dev/nvme4n1 from /dev/md127, array will be failed.
Personalities : [raid6] [raid5] [raid4] [raid1]
md126 : active raid1 nvme6n1[0]
5242880 blocks super external:/md127/0 [2/1] [_U]
md127 : inactive nvme6n1[1](S) nvme4n1[0](S)
10402 blocks super external:imsm
unused devices: <none>
mdadm: Cannot remove /dev/nvme6n1 from /dev/md126, array will be failed.
mdadm: hot …
```

sysfs: add sysfs_open_memb_attr()

---

managemon.c
mdadm.h
mdmon.h
monitor.c

Starting from [1], kernel requires suspend lock on member drive remove path. It causes deadlock with external management because monitor thread may be locked on suspend and is unable to switch array to active, for example if badblock is reported in this time.
It is blocking action now, so it must be delegated to managemon thread but we must ensure that monitor does metadata update first, just after detecting faulty.
This patch adds appropriative support. Monitor thread detects "faulty", and updates the metadata. After that it is asking manager thread to remove the device.
Manager should not activate recovery for the device if it is not able to remove all devices marked to remove.
Because it is blocking action in kernel now, looks like that retries are no longer required. There is no …

mdmon: delegate removal to managemon

---

mdopen.c

After mentioned patch, this condition get opposite meaning and it is blocking creation in cases where it was supported.
Remove it now.
Fixes: 119cdcad049e ("mdadm: drop auto= support")

mdopen: remove wrong condition

---

tests/07reshape5intr
tests/func.sh
tests/imsm-grow-template

When grow-continue process is on, the sync_action represents value which means that recovery is in progress. When grow-continue does not finish, even if sync_action is not reshape anymore, test should fail.

func.sh: do not hang when grow-continue can't finish

---

.github/tools/run_mdadm_tests.sh
.github/workflows/tests.yml

Use prepared VM machine in GitHub actions to run mdadm tests on it.

CI: use self-hosted runner to run tests

---

super-intel.c

mdadm -C /dev/md/imsm0 -e imsm -n 2 /dev/nvme5n1 /dev/nvme4n1 -R mdadm -C /dev/md/r0d2 -l 0 -n 2 /dev/nvme5n1 /dev/nvme4n1 -R *** buffer overflow detected ***: terminated
Aborted (core dumped)
Issue is related to D_FORTIFY_SOURCE=3 flag and depends on environment, especially compiler version. In function active_arrays_by_format length of path buffer is calculated dynamically based on parameters, while PATH_MAX is used in snprintf, this is my lead to buffer overflow.
It is fixed by change dynamic length calculation, to use define PATH_MAX for path length.

platform-intel: fix buffer overflow

---

tests/func.sh
tests/templates/names_template

Mdadm supports DEVNODE in multiple form, we cannot trust that because it does not always reflect name in metadata. Tests are defining clear expectations- we must use them.
Do foreign verification against WANTED_NAME instead of passed DEVNODE.

tests: fix "foreign" verification for nameing tests.

---

.github/tools/run_mdadm_tests.sh
.github/workflows/tests.yml

Currently, if error is returned by test command, execution of other
steps is aborted. In that case, continue-on-error safe artifict but
return error later and fail the job.
If executions passed, there are no artifacts to safe, therefore do not
safe them.

CI: improve handling of failed/succussed executions.

---

Assemble.c
Build.c
Create.c
Grow.c
Incremental.c
Manage.c
bitmap.c
config.c
mdadm.c
mdadm.h
tests/04update-uuid
tests/05r1-re-add-nosuper

ML: https://lore.kernel.org/linux-raid/20241202015913.3815936-1-yukuai1@huaweicloud.com/T/#t

Kuai's custom bitmap patches

---

CHANGELOG.md
ReadMe.c
mdadm.8.in
mdmon.8

```
WARNING:COMMIT_MESSAGE: Missing commit description - Add an appropriate one
Error: WARNING:COMMIT_MESSAGE: Missing commit description - Add an appropriate one
```
This is fine in this case. It is to previous releases style. I can eventually copy title to description.
For highlights, see changelog. The content bellow will be added to `[ANNOUNCE]`, please review:
```
Other news:
Customer Github runner is now available thanks to Paul Luse. Kinga Stefaniuk enabled it for mdadm. We are
still missing communication between Mailing List and Github.
Sadly, Intel decided to move VROC to maintenance. It means that part of the team will be disbanded
and project will be discontinued in next years. I'm leaving VROC team.
I would like to still maintain mdadm and just be here as long community as it …
```

Release mdadm-4.4

---

Assemble.c
Incremental.c
bitmap.c

Handle variable going out of scope leaks the handle.

Coverity fixes resources leaks

---

.github/tools/.checkpatch.conf
Incremental.c
Manage.c
mdadm.h
monitor.c
sysfs.c
util.c

This is a first part of HOT_REMOVE_DISK/SET_FAULTY rework. The goal is to not execute HOT_REMOVE_DISK ioctl on `mdadm --remove` path with container.
This PR changes following:
- Manage_subdevs will not execute HOT_REMOVE_IOCTL with "faulty" (not needed because sysfs way is same reliable).
- Incremental_remove will implement remove logic directly.

Incremental: do not call Manage_subdevs() from IncrementalRemove()

---

MAINTAINERS

keep track of people to contact when dealing with mdadm issues.

mdadm: add MAINTAINERS file Create a maintainers file to

---

mdadm.8.in

Remove  external bitmap support from manual.
Fixes: #138

mdadm.man: Remove external bitmap

---

udev-md-raid-arrays.rules

dracut installs in the initrd a custom udev rule only to set this option [1]. The main purpose is that if an MD device is activated in the initrd, its properties are kept on the udev database after the transition from the initrd to the rootfs. This was added to fix detection issues when LVM is on top.
This patch would allow to remove the custom udev rule shipped by dracut (`63-md-raid-arrays.rules` is already being installed in the initrd), and it will also benefit other initrd generators that do not want to create custom udev rules.
[1] https://github.com/dracutdevs/dracut/blob/5d2bda46f4e75e85445ee4d3bd3f68bf966287b9/modules.d/90mdraid/59-persistent-storage-md.rules#L23

udev: persist properties of MD devices after switch_root

---

mdadm.c

For the case mdadm --grow with --add, the s.btype should not be initialized yet, hence BitmapUnknown should be checked instead of BitmapNone.
Noted that this behaviour should only support by md-linear, which is removed from kernel, howerver, it turns out md-linear is used widely in home NAS and we're planning to reintroduce it soon.
Fixes: 581ba1341017 ("mdadm: remove bitmap file support")
PR to test Kuai's changes.

mdadm: fix --grow with --add for linear

---

platform-intel.c

The legacy option ROM memory range from 0xc0000-0xeffff is not defined on UEFI machines so don't attempt to scan it. This avoids lockdown log spam when Secure Boot is enabled (avoids use of /dev/mem).

platform-intel: Disable legacy option ROM scan on UEFI machines

---

super-ddf.c
xmalloc.c
xmalloc.h

**Added logic to check the last 512 bytes of the device (`dsize -
512`) first**
for the presence of the DDF header (`DDF_HEADER_MAGIC`).
- If the header is found, the function immediately proceeds without performing a broader search.
- Validates the magic value after reading the 512 bytes.
**Fallback to searching the last 32MB of the device**
using the  `search_for_ddf_headers` function when the last 512 bytes do not contain the header.
- Performs a block-by-block search to locate the DDF header within the specified region.
see also: https://github.com/md-raid-utilities/mdadm/issues/135

super-ddf: optimize DDF header search for widely used RAID controllers

---

super1.c
tests/05r1-add-badblocks

When adding a disk to a RAID1 array, the metadata is read from the existing member disks for sync. However, only the bad_blocks flag are copied, the bad_blocks records are not copied, so the bad_blocks records are all zeros. The kernel function super_1_load() detects bad_blocks flag and reads the bad_blocks record, then sets the bad block using badblocks_set().
After the kernel commit 1726c7746783 (badblocks: improve badblocks_set() for multiple ranges handling) if the length of a bad_blocks record is 0, it will return a failure. Therefore the device addition will fail.
So when adding a new disk, some flags cannot be sync and need to be clead.

super1: Clear extra flags when initializing metadata

---

super-intel.c

Support for RAID10 with +4 disks in IMSM introduced an inconsistency
between the VROC UEFI driver and Linux IMSM. VROC UEFI does not
support RAID10 with +4 disks, therefore appropriate protections were
added to the mdadm IMSM code that results in skipping processing of
such RAID in the UEFI phase. Unfortunately the case of migration
RAID0 2 disks to RAID10 4 disks was omitted, this case requires
maintaining compatibility with the VROC UEFI driver because it is
supported.
For RAID10 +4 disk the MPB_ATTRIB_RAID10_EXT attribute is set in the
metadata, thanks to which the UEFI driver does not process such RAID.
In the series adding support, a new metadata raid level value
IMSM_T_RAID10 was also introduced. It is not recognized by VROC UEFI.
The issue is caused by the fact that in the case of …

imsm: Fix RAID0 to RAID10 migration

---

Build.c
Create.c
maps.c
mdadm.h
super0.c
super1.c
tests/00raid0

It is not currently possible to create a RAID0 with 0.90 metadata. This is because 0.90 cannot specify the layout of RAID0 (it is traditionally ignored) and different kernels do different things with RAID0 layouts.
However it should be possible to use --layout=dangerous as that acknowledges the risk.
It also should be possible to create a RAID0 with all devices the same size because in that case all layouts are identical.
The metadata handler can only check that all devices are the same size quite late - in write_init_super().  By that time the default is currently set - set to a value that super0 cannot handle.
So this patch delays the setting of the default value and leave it for the metadata handler (or for the Build handler).
super1 selects ORIG in that case.
intel and ddf don't …

Allow RAID0 to be created with v0.90 metadata #161

---

Create.c
Detail.c
Examine.c
Grow.c
Kill.c
Makefile
Manage.c
Query.c
README.md
mdadm.h
mdmonitor.c
super1.c
udev.c

For a years we redefined these headers in mdadm. It was efficient way to handle implementation of new features, we didn't rely on kernel during compilation. It is huge mess now.
We should reuse the headers exported to integrate driver and mdadm better.  Add them and remove local headers.
This PR requires deep review and testing. @ncroxon, @XiaoNi87 I need your support on this.

mdadm: use <linux/raid> headers

---

util.c

Since 25aa732 ("mdadm: numbered names verification"), it is not possible any more to create arrays /dev/md${N} with N >= 127. The limit has later been increased to 1024, which is also artificial. The error message printed by mdadm is misleading, as the problem is not POSIX compatibility here.
mdadm: Value "/dev/md9999" cannot be set as devname. Reason: Not POSIX compatible.
Given that mdadm creates an array with minor number ${N} if the argument is /dev/md${N}, the natural limit for the number is the highest minor number available, which is (1 << MINORBITS) with MINORBITS=20 on Linux.
I'm aware that the error message above will go away with #165. I believe that this has some merit in its own right (be it only because of the name / minor number equivalence), therefore I'm proposing it …

mdadm: allow any valid minor number in md device name

---

config.c
mdadm.8.in
super-intel.c
tests/00confnames

Neil Brown in #159 pointed that mdadm should been keep in base utility style, allowing much more with no strict limitations until absolutely necessary to prevent crashes.
This view, supported with regression https://github.com/md-raid-utilities/mdadm/pull/160 caused by POSIX portable
character set requirement leads me to revert it.
Revert the POSIX portable character set verification of name and
devname. Make it IMSM only.
Fixes: #159 
Fixes: #160

mdadm: removed POSIX check

---

Assemble.c

It stops the array which is just created. From the comment it wants to stop the array if it has no content. But it hasn't added member disks, so it's a clean array. It's meaningless to do it.

mdadm/assemble: Don't stop array after creating it

---

misc/mdcheck
systemd/mdcheck_continue.service
systemd/mdcheck_continue.timer
systemd/mdcheck_start.service
systemd/mdcheck_start.timer

This set fixes a few issues I've found with the `mdcheck_start` and `mdcheck_continue` systemd units.
- `systemctl start` hangs for these units until the check has finished, or ctrl-c is pressed.
- `systemctl stop` for these units may also hang for several minutes while the `mdcheck` script is executing `sleep`
- when these units are stopped with `systemctl stop`, the actual check in the kernel continues to run. Subsequent (re)starting these units has no effect because they see the kernel check already running.
- a check that has not been finished for an entire month (perhaps due to downtime) will be restarted from position 0 rather than picked up.

mdcheck fixes

---

mdmonitor.c

Since commit e702f392959d ("Mdmonitor: Fix segfault"), when configuration files used non-absolute ARRAY device names, commands like `mdadm --monitor --scan` failed with `mdadm: error opening devname: No such file or directory` unless run from the `/dev/md` directory.

Fix --monitor --scan with relative ARRAY devnames

---

mdmonitor.c

After commit
<https://github.com/md-raid-utilities/mdadm/commit/84d969be8f6d8a345b75f558fad26e4f62a558f6>
it is no longer possible to monitor md devices with device files like
`/dev/md0`, `/dev/md1` ... which have no corresponding symbolic link in
directory `/dev/md/`
The proposed pull request fixes this beviour.
Create block devices for testing:
```
```
```
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE   DIO LOG-SEC
/dev/loop1         0      0         0  0 /tmp/d1.bin   0     512
/dev/loop0         0      0         0  0 /tmp/d0.bin   0     512
```
Create RAID-1 array `/dev/md0`:
```
mdadm: Note: this array has metadata at the start and
may not be suitable as a boot device.  If you plan to
store '/boot' on this device please ensure that
your boot-loader understands md/v1.x metadata, …
```

Re-enable mdadm --monitor ... for /dev/mdX
